// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllLabels() {
  return window['go']['main']['App']['AllLabels']();
}

export function ChooseMediaRoot() {
  return window['go']['main']['App']['ChooseMediaRoot']();
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function ConnectCookies() {
  return window['go']['main']['App']['ConnectCookies']();
}

export function CookieStatus() {
  return window['go']['main']['App']['CookieStatus']();
}

export function Enqueue(arg1) {
  return window['go']['main']['App']['Enqueue'](arg1);
}

export function Enumerate(arg1) {
  return window['go']['main']['App']['Enumerate'](arg1);
}

export function Favorites() {
  return window['go']['main']['App']['Favorites']();
}

export function GetModelInfo(arg1) {
  return window['go']['main']['App']['GetModelInfo'](arg1);
}

export function Import(arg1, arg2) {
  return window['go']['main']['App']['Import'](arg1, arg2);
}

export function ImportFilesDialog(arg1) {
  return window['go']['main']['App']['ImportFilesDialog'](arg1);
}

export function ImportFolderDialog() {
  return window['go']['main']['App']['ImportFolderDialog']();
}

export function ImportPhotosDialog(arg1) {
  return window['go']['main']['App']['ImportPhotosDialog'](arg1);
}

export function LabelCounts() {
  return window['go']['main']['App']['LabelCounts']();
}

export function MarkWatched(arg1, arg2) {
  return window['go']['main']['App']['MarkWatched'](arg1, arg2);
}

export function MediaBase() {
  return window['go']['main']['App']['MediaBase']();
}

export function MediaRootPath() {
  return window['go']['main']['App']['MediaRootPath']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PhotosByModel(arg1) {
  return window['go']['main']['App']['PhotosByModel'](arg1);
}

export function Queue() {
  return window['go']['main']['App']['Queue']();
}

export function RecentlyDownloaded() {
  return window['go']['main']['App']['RecentlyDownloaded']();
}

export function RecentlyWatched() {
  return window['go']['main']['App']['RecentlyWatched']();
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveModelInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveModelInfo'](arg1, arg2, arg3);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetCookieSpec(arg1) {
  return window['go']['main']['App']['SetCookieSpec'](arg1);
}

export function SetFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2, arg3);
}

export function SetLabels(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLabels'](arg1, arg2, arg3);
}

export function SetModelCover(arg1, arg2) {
  return window['go']['main']['App']['SetModelCover'](arg1, arg2);
}

export function SetModels(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModels'](arg1, arg2, arg3);
}

export function SetTitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTitle'](arg1, arg2, arg3);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function VideosByLabel(arg1) {
  return window['go']['main']['App']['VideosByLabel'](arg1);
}

export function VideosByModel(arg1) {
  return window['go']['main']['App']['VideosByModel'](arg1);
}

export function VideosBySite(arg1) {
  return window['go']['main']['App']['VideosBySite'](arg1);
}
