// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIBase() {
  return window['go']['main']['App']['APIBase']();
}

export function ChooseMediaRoot() {
  return window['go']['main']['App']['ChooseMediaRoot']();
}

export function ConnectCookies() {
  return window['go']['main']['App']['ConnectCookies']();
}

export function Import(arg1, arg2) {
  return window['go']['main']['App']['Import'](arg1, arg2);
}

export function ImportFilesDialog(arg1) {
  return window['go']['main']['App']['ImportFilesDialog'](arg1);
}

export function ImportFolderDialog() {
  return window['go']['main']['App']['ImportFolderDialog']();
}

export function ImportPhotosDialog(arg1) {
  return window['go']['main']['App']['ImportPhotosDialog'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function Types() {
  return window['go']['main']['App']['Types']();
}
