// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseMediaRoot() {
  return window['go']['main']['App']['ChooseMediaRoot']();
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function ConnectCookies() {
  return window['go']['main']['App']['ConnectCookies']();
}

export function CookieStatus() {
  return window['go']['main']['App']['CookieStatus']();
}

export function Enqueue(arg1) {
  return window['go']['main']['App']['Enqueue'](arg1);
}

export function Enumerate(arg1) {
  return window['go']['main']['App']['Enumerate'](arg1);
}

export function MarkWatched(arg1, arg2) {
  return window['go']['main']['App']['MarkWatched'](arg1, arg2);
}

export function MediaRootPath() {
  return window['go']['main']['App']['MediaRootPath']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Queue() {
  return window['go']['main']['App']['Queue']();
}

export function RecentlyDownloaded() {
  return window['go']['main']['App']['RecentlyDownloaded']();
}

export function RecentlyWatched() {
  return window['go']['main']['App']['RecentlyWatched']();
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetCookieSpec(arg1) {
  return window['go']['main']['App']['SetCookieSpec'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function Videos(arg1, arg2) {
  return window['go']['main']['App']['Videos'](arg1, arg2);
}

export function VideosBySite(arg1) {
  return window['go']['main']['App']['VideosBySite'](arg1);
}
