// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {downloader} from '../models';
import {library} from '../models';

export function ChooseMediaRoot():Promise<string>;

export function ClearFinished():Promise<void>;

export function ConnectCookies():Promise<main.CookieStatus>;

export function CookieStatus():Promise<main.CookieStatus>;

export function Enqueue(arg1:string):Promise<string>;

export function Enumerate(arg1:string):Promise<Array<downloader.RemoteItem>>;

export function MarkWatched(arg1:string,arg2:string):Promise<void>;

export function MediaRootPath():Promise<string>;

export function Models():Promise<Array<library.Model>>;

export function OpenFolder(arg1:string):Promise<void>;

export function Queue():Promise<Array<downloader.Job>>;

export function RecentlyDownloaded():Promise<Array<library.Video>>;

export function RecentlyWatched():Promise<Array<library.Video>>;

export function RemoveJob(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function Search(arg1:string):Promise<Array<library.Video>>;

export function SetCookieSpec(arg1:string):Promise<void>;

export function Stats():Promise<library.Stats>;

export function Videos(arg1:string,arg2:string):Promise<Array<library.Video>>;

export function VideosBySite(arg1:string):Promise<Array<library.Video>>;
