// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function APIBase():Promise<string>;

export function ChooseMediaRoot():Promise<string>;

export function ConnectCookies():Promise<core.CookieStatus>;

export function Import(arg1:Array<string>,arg2:string):Promise<void>;

export function ImportFilesDialog(arg1:string):Promise<void>;

export function ImportFolderDialog():Promise<void>;

export function ImportPhotosDialog(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function Types():Promise<main.boundTypes>;
